"""empty message

Revision ID: 7f8297cdaa7f
Revises: 
Create Date: 2021-11-10 16:12:28.881530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8297cdaa7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('token')
    )
    op.create_table('tb_branches',
    sa.Column('branchid', sa.Integer(), nullable=False),
    sa.Column('branchname', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phoneno', sa.String(length=20), nullable=True),
    sa.Column('createdon', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('editedon', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('editedby', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('branchid')
    )
    op.create_index(op.f('ix_tb_branches_createdby'), 'tb_branches', ['createdby'], unique=False)
    op.create_index(op.f('ix_tb_branches_editedby'), 'tb_branches', ['editedby'], unique=False)
    op.create_table('tb_def',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('skey', sa.String(length=200), nullable=True),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('editedon', sa.DateTime(), nullable=True),
    sa.Column('isactive', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('isvisible', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tb_profile',
    sa.Column('profileid', sa.Integer(), nullable=False),
    sa.Column('profilename', sa.String(length=60), nullable=True),
    sa.Column('profiledesc', sa.String(length=200), nullable=True),
    sa.Column('profilestatus', sa.Integer(), server_default='0', nullable=False),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('editedon', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=False),
    sa.Column('editedby', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('profileid'),
    sa.UniqueConstraint('profilename'),
    sa.UniqueConstraint('profilename')
    )
    op.create_index(op.f('ix_tb_profile_createdby'), 'tb_profile', ['createdby'], unique=False)
    op.create_index(op.f('ix_tb_profile_editedby'), 'tb_profile', ['editedby'], unique=False)
    op.create_table('tb_misc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('parentid', sa.Integer(), nullable=False),
    sa.Column('skey', sa.String(length=200), nullable=True),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('editedon', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('isactive', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('isvisible', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['parentid'], ['tb_def.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tb_users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('fullname', sa.String(length=60), nullable=False),
    sa.Column('pwd', sa.String(length=128), nullable=True),
    sa.Column('mobileno', sa.String(length=60), nullable=False),
    sa.Column('profileid', sa.Integer(), nullable=False),
    sa.Column('idtype', sa.String(length=60), nullable=False),
    sa.Column('idno', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('editedon', sa.DateTime(), nullable=True),
    sa.Column('loginattempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lastpwdchange', sa.DateTime(), nullable=True),
    sa.Column('access_type', sa.Enum('MOBILENO', 'EMAIL'), server_default='MOBILENO', nullable=False),
    sa.Column('countrydetails', sa.JSON(), nullable=True),
    sa.Column('isauthorized', sa.Integer(), server_default='0', nullable=False),
    sa.Column('branchid', sa.Integer(), nullable=False),
    sa.Column('accessbranch', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profileid'], ['tb_profile.profileid'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_tb_users_branchid'), 'tb_users', ['branchid'], unique=False)
    op.create_index(op.f('ix_tb_users_email'), 'tb_users', ['email'], unique=True)
    op.create_index(op.f('ix_tb_users_fullname'), 'tb_users', ['fullname'], unique=False)
    op.create_index(op.f('ix_tb_users_idno'), 'tb_users', ['idno'], unique=True)
    op.create_index(op.f('ix_tb_users_mobileno'), 'tb_users', ['mobileno'], unique=True)
    op.create_index(op.f('ix_tb_users_username'), 'tb_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_users_username'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_mobileno'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_idno'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_fullname'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_email'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_branchid'), table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_table('tb_misc')
    op.drop_index(op.f('ix_tb_profile_editedby'), table_name='tb_profile')
    op.drop_index(op.f('ix_tb_profile_createdby'), table_name='tb_profile')
    op.drop_table('tb_profile')
    op.drop_table('tb_def')
    op.drop_index(op.f('ix_tb_branches_editedby'), table_name='tb_branches')
    op.drop_index(op.f('ix_tb_branches_createdby'), table_name='tb_branches')
    op.drop_table('tb_branches')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
